### ISSUE TITLE
The list is too big.

### ISSUE THREAD

**Issue by olistik** [zenkay/bigdata-ecosystem#6]
The fact that it refers to BigData doesn't imply that it should be big as well. #metaPhunIntended

**Comment by olistik** [comment]
At least put a reference to the list in the list itself.

**Comment by zenkay** [comment]
This should be a open dataset. You can use it, filter it or create another list based on a subset of contents (a lot of single JSON files into ```projects-data``` and ```paper-data```.

The Github README is a quick and unfiltered preview of what it contains.
