### ISSUE TITLE
Should defunct projects be listed?

### ISSUE THREAD

**Issue by mspiegel** [zenkay/bigdata-ecosystem#7]
I was going to submit a pull request that removes FoundationDB but I thought that maybe there should be a notation to indicate that the product is no longer active. FoundationDB the company was acquired by Apple in March 2015. FoundationDB the product is no longer available.

**Comment by zenkay** [comment]
Hi Michael! Thank you for your question :) I never think about "dead" projects. FoundationDB is not the only dead project inside the list and I never think to clean up them.

I suppose we can handle them using a tag or insert a specific property and show the project strikethrough. Any suggestion?

I'm going to release an update in the coming days and I'd be happy to implement this new feature and merge your PR ;)
